"""Operation status

Revision ID: 2de045088fcc
Revises: 9af68bf28f54
Create Date: 2026-06-04 15:45:42.949098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de045088fcc'
down_revision: Union[str, Sequence[str], None] = '9af68bf28f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    operationstatus = postgresql.ENUM('ACTIVE', 'CANCELED', 'FINISHED', name='operationstatus')
    operationstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('operation_history', sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'FINISHED', name='operationstatus'), nullable=False))
    op.add_column('operation_history', sa.Column('last_update_at', sa.DateTime(), nullable=False))
    op.drop_column('operation_history', 'operation_type')
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("""
            ALTER TABLE operation_history
            ADD CONSTRAINT exclude_no_overlap
            EXCLUDE USING gist (
                resource_id WITH =,
                tsrange(booked_from, booked_to) WITH &&
            )
            WHERE (status = 'ACTIVE');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE operation_history
            DROP CONSTRAINT IF EXISTS exclude_no_overlap;
        """
    )
    op.add_column('operation_history', sa.Column('operation_type', postgresql.ENUM('book', 'cancel', name='operation_type_enum'), nullable=False))
    op.drop_column('operation_history', 'last_update_at')
    op.drop_column('operation_history', 'status')
    postgresql.ENUM(name='operationstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
