"""Indexes

Revision ID: 9af68bf28f54
Revises: f2e2b0ba8fae
Create Date: 2026-06-04 13:24:33.341649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af68bf28f54'
down_revision: Union[str, Sequence[str], None] = 'f2e2b0ba8fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_operation_dates', 'operation_history', ['booked_from', 'booked_to'], unique=False)
    op.create_index(op.f('ix_operation_history_booker_id'), 'operation_history', ['booker_id'], unique=False)
    op.create_index(op.f('ix_operation_history_resource_id'), 'operation_history', ['resource_id'], unique=False)
    op.drop_constraint(op.f('operation_history_booker_id_fkey'), 'operation_history', type_='foreignkey')
    op.drop_constraint(op.f('operation_history_resource_id_fkey'), 'operation_history', type_='foreignkey')
    op.create_foreign_key(None, 'operation_history', 'user', ['booker_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'operation_history', 'resource', ['resource_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resource_name_key'), 'resource', type_='unique')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.create_unique_constraint(op.f('resource_name_key'), 'resource', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'operation_history', type_='foreignkey')
    op.drop_constraint(None, 'operation_history', type_='foreignkey')
    op.create_foreign_key(op.f('operation_history_resource_id_fkey'), 'operation_history', 'resource', ['resource_id'], ['id'])
    op.create_foreign_key(op.f('operation_history_booker_id_fkey'), 'operation_history', 'user', ['booker_id'], ['id'])
    op.drop_index(op.f('ix_operation_history_resource_id'), table_name='operation_history')
    op.drop_index(op.f('ix_operation_history_booker_id'), table_name='operation_history')
    op.drop_index('idx_operation_dates', table_name='operation_history')
    # ### end Alembic commands ###
