"""Booking description

Revision ID: f133e83864aa
Revises: 2de045088fcc
Create Date: 2026-06-07 16:31:57.438923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f133e83864aa'
down_revision: Union[str, Sequence[str], None] = '2de045088fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_history', sa.Column('description', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_history', 'description')
    # ### end Alembic commands ###
