"""Initial tables

Revision ID: f2e2b0ba8fae
Revises: 78d3f265995f
Create Date: 2026-04-28 21:05:29.598559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e2b0ba8fae'
down_revision: Union[str, Sequence[str], None] = '78d3f265995f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
