
services:
  web:
    build: ./src
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://app:app@db/web_fastapi_dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine3.23
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=web_fastapi_dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d web_fastapi_dev" ]
      interval: 5s
      timeout: 5s
      retries: 5

    
volumes:
  postgres_data: